// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp2RXwOBYkjaOz1z1edNyvVs0PQuDQU90',
    appId: '1:379960450826:web:8668e7d8b3f8dffe3ce4f3',
    messagingSenderId: '379960450826',
    projectId: 'test-346c3',
    authDomain: 'test-346c3.firebaseapp.com',
    databaseURL: 'https://test-346c3.firebaseio.com',
    storageBucket: 'test-346c3.appspot.com',
    measurementId: 'G-L57X9DC0P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5DiD47v5hir5ZYfuvh4ZlvC9Ldjc7YV4',
    appId: '1:379960450826:android:2275dd31d799c67f3ce4f3',
    messagingSenderId: '379960450826',
    projectId: 'test-346c3',
    databaseURL: 'https://test-346c3.firebaseio.com',
    storageBucket: 'test-346c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPswfm5xcRk8t1cOHODWUI9qNOXo-eHXU',
    appId: '1:379960450826:ios:c08a558c9d58b89a3ce4f3',
    messagingSenderId: '379960450826',
    projectId: 'test-346c3',
    databaseURL: 'https://test-346c3.firebaseio.com',
    storageBucket: 'test-346c3.appspot.com',
    iosClientId: '379960450826-ohsv8oca1uip0m308i91h6gc21kpph4v.apps.googleusercontent.com',
    iosBundleId: 'com.hw2.app',
  );
}
